/**
 * PWA Forge — Deploy Worker (v2: Git-connected)
 * -----------------------------------------------
 * Receives generated PWA files from the Forge tool and publishes them by:
 *   1. Creating a new GitHub repo (via GitHub's REST API)
 *   2. Pushing the files into it (via GitHub's Contents API)
 *   3. Creating a Cloudflare Pages project sourced from that repo
 *      (Cloudflare's officially documented git-source API, not the
 *      internal direct-upload sequence used in the previous version)
 *
 * Cloudflare then builds and deploys automatically, same as any
 * Git-connected Pages project. First build after creation typically
 * takes 30-90 seconds before the URL resolves.
 *
 * REQUIRES, one-time, done via the dashboards (not in this file):
 *   - The Cloudflare Pages GitHub App installed on your GitHub account
 *     with access to "All repositories" (Workers & Pages -> Create ->
 *     Pages -> Connect to Git -> GitHub -> Install & Authorize)
 *   - Three Worker secrets (Settings -> Variables and Secrets):
 *       CF_API_TOKEN   = Cloudflare API token (Account -> Pages -> Edit)
 *       CF_ACCOUNT_ID  = your Cloudflare account ID
 *       GITHUB_TOKEN   = a GitHub personal access token with repo-create
 *                        permission (classic PAT, "repo" scope)
 */

const CF_API = 'https://api.cloudflare.com/client/v4';
const GH_API = 'https://api.github.com';

export default {
  async fetch(request, env) {
    const cors = {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    };
    if (request.method === 'OPTIONS') return new Response(null, { headers: cors });

    const url = new URL(request.url);
    if (url.pathname !== '/deploy' || request.method !== 'POST') {
      return new Response(JSON.stringify({ error: 'POST /deploy only' }), {
        status: 404, headers: { ...cors, 'Content-Type': 'application/json' }
      });
    }

    if (!env.CF_API_TOKEN || !env.CF_ACCOUNT_ID || !env.GITHUB_TOKEN) {
      return new Response(JSON.stringify({ error: 'Worker is missing CF_API_TOKEN / CF_ACCOUNT_ID / GITHUB_TOKEN secrets' }), {
        status: 500, headers: { ...cors, 'Content-Type': 'application/json' }
      });
    }

    try {
      const { projectName, files } = await request.json();
      if (!projectName || !files || typeof files !== 'object') {
        throw new Error('Request must include projectName and a files map');
      }

      const slug = projectName.toLowerCase()
        .replace(/[^a-z0-9-]/g, '-')
        .replace(/-+/g, '-')
        .replace(/^-|-$/g, '')
        .slice(0, 55) || 'pwa-app';

      const ghHeaders = {
        'Authorization': `Bearer ${env.GITHUB_TOKEN}`,
        'Accept': 'application/vnd.github+json',
        'Content-Type': 'application/json',
        'User-Agent': 'pwa-forge-deploy-worker'
      };

      // 1. Who are we pushing as?
      const meRes = await fetch(`${GH_API}/user`, { headers: ghHeaders });
      if (!meRes.ok) throw new Error('GitHub auth failed: ' + await meRes.text());
      const owner = (await meRes.json()).login;

      // 2. Create the repo (auto_init so it has a default branch to push into)
      const repoRes = await fetch(`${GH_API}/user/repos`, {
        method: 'POST', headers: ghHeaders,
        body: JSON.stringify({ name: slug, private: false, auto_init: true, description: 'Generated by PWA Forge' })
      });
      if (!repoRes.ok) throw new Error('Could not create GitHub repo: ' + await repoRes.text());
      const branch = (await repoRes.json()).default_branch || 'main';

      // 3. Push every file via the Contents API
      for (const [rawPath, b64] of Object.entries(files)) {
        const path = rawPath.replace(/^\/+/, '');
        const putRes = await fetch(`${GH_API}/repos/${owner}/${slug}/contents/${path}`, {
          method: 'PUT', headers: ghHeaders,
          body: JSON.stringify({ message: `add ${path}`, content: b64, branch })
        });
        if (!putRes.ok) throw new Error(`Could not push ${path}: ` + await putRes.text());
      }

      // 4. Create a Cloudflare Pages project sourced from that repo
      const cfHeaders = { 'Authorization': `Bearer ${env.CF_API_TOKEN}`, 'Content-Type': 'application/json' };
      const cfRes = await fetch(`${CF_API}/accounts/${env.CF_ACCOUNT_ID}/pages/projects`, {
        method: 'POST', headers: cfHeaders,
        body: JSON.stringify({
          name: slug,
          production_branch: branch,
          source: {
            type: 'github',
            config: {
              owner,
              repo_name: slug,
              production_branch: branch,
              deployments_enabled: true
            }
          }
        })
      });
      const cfData = await cfRes.json();
      if (!cfRes.ok || !cfData.success) {
        throw new Error('Cloudflare project creation failed: ' + JSON.stringify(cfData.errors || cfData));
      }

      const liveUrl = `https://${slug}.pages.dev`;
      return new Response(JSON.stringify({ url: liveUrl, repo: `https://github.com/${owner}/${slug}` }), {
        headers: { ...cors, 'Content-Type': 'application/json' }
      });

    } catch (err) {
      return new Response(JSON.stringify({ error: err.message || String(err) }), {
        status: 500, headers: { ...cors, 'Content-Type': 'application/json' }
      });
    }
  }
};
